# Generated by Django 3.0.2 on 2021-08-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.FloatField()),
                ('status', models.CharField(choices=[('nl', 'Не просмотрено'), ('l', 'Просмотрено'), ('p', 'Запланировано'), ('t', 'Брошено')], default='nl', max_length=30)),
            ],
        ),
    ]
