# Generated by Django 3.0.2 on 2021-08-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(blank=True, choices=[('nl', 'Не просмотрено'), ('l', 'Просмотрено'), ('p', 'Запланировано'), ('t', 'Брошено')], default='nl', max_length=30, null=True),
        ),
    ]
