# Generated by Django 3.0.2 on 2021-08-11 12:11

import Cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0002_auto_20210810_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Cinema.models.get_timestamp_path),
        ),
    ]
