# Generated by Django 3.0.2 on 2021-08-12 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cinema', '0003_auto_20210811_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.RemoveField(
            model_name='film',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='film',
            name='status',
        ),
        migrations.AddField(
            model_name='film',
            name='url',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nl', 'Не просмотрено'), ('l', 'Просмотрено'), ('p', 'Запланировано'), ('t', 'Брошено')], default='nl', max_length=30)),
                ('filmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.Film')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
