# Generated by Django 3.0.2 on 2021-08-13 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0004_auto_20210812_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name': 'Статус фильма пользователя', 'verbose_name_plural': 'Статусы фильмов пользователей'},
        ),
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.Film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='Cinema.Genre'),
        ),
    ]
