# Generated by Django 3.0.2 on 2021-08-13 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cinema', '0005_auto_20210813_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStatus',
            new_name='UserFilmStatus',
        ),
    ]
