# Generated by Django 3.0.2 on 2021-08-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0006_auto_20210813_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.Film')),
            ],
            options={
                'verbose_name': 'Рейтинг фильма',
                'verbose_name_plural': 'Рейтинг фильмов',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='ratingfilm',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.RatingStar'),
        ),
    ]
