# Generated by Django 3.0.2 on 2021-08-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0007_auto_20210813_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingfilm',
            name='star',
        ),
        migrations.AddField(
            model_name='ratingfilm',
            name='stars',
            field=models.ManyToManyField(to='Cinema.RatingStar'),
        ),
    ]
