# Generated by Django 3.0.2 on 2021-08-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0008_auto_20210813_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
