# Generated by Django 3.0.2 on 2021-08-16 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cinema', '0015_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='filmId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.Film'),
        ),
        migrations.AlterField(
            model_name='review',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
