# Generated by Django 3.0.2 on 2021-08-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0016_auto_20210816_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
