# Generated by Django 3.0.2 on 2021-08-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0017_auto_20210817_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-rating'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='filmId',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='userId',
            new_name='user',
        ),
    ]
