# Generated by Django 3.0.2 on 2021-08-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0018_auto_20210817_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Колекция фильмов',
                'verbose_name_plural': 'Колекции фильмов',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='filmCollection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cinema.FilmCollection'),
        ),
    ]
