# Generated by Django 3.0.2 on 2021-08-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0019_auto_20210819_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmcollection',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
