# Generated by Django 3.2.6 on 2021-08-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalCabinet', '0002_alter_userprivacy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivacy',
            name='isPrivacy',
            field=models.BooleanField(default=False),
        ),
    ]
